### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by johnnychen94** [VukanJ/bibtex-helper#1]
I've seen that there are snippets in your codes, however, when typing "book" there is no response at all. I'm not sure, perhaps there is something necessary miss (code or dependency package).
The current installed latex-related packages are: bibtex-helper, language-latex, latex, linter-spell-latex.

**Comment by VukanJ** [comment]
Try typing "book" and hitting Tab anyway. I am not getting an autocomplete response either. I could not figure it out, yet. There seem to be some issues with autocomplete-plus and bibtex. I will post a fix as soon as I find one. Try disabling "Enable Built-In Provider" in your autocomplete-plus settings (this didn't fix it for me though).
